apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-db-init-config
  namespace: ktask
data:
  init-resource-svc-db.sql: |
    CREATE DATABASE resource_svc_db;
    \c resource_svc_db;
    CREATE TABLE resource
    (
    id         SERIAL PRIMARY KEY,
    audio_data BYTEA NOT NULL
    );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: song-db-init-config
  namespace: ktask
data:
  init-song-svc-db.sql: |
    CREATE DATABASE song_svc_db;
    \c song_svc_db;
    CREATE TABLE song
    (
    id           SERIAL PRIMARY KEY,
    resource_id  INT,
    artist       VARCHAR(255),
    name         VARCHAR(255),
    album        VARCHAR(255),
    release_year VARCHAR(4),
    duration     VARCHAR(10)
    );